# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name unique_vector
#' @noRd
#'
NULL

#' @name set_diff
#' @noRd
#'
NULL

#' @name c_basis1
#' @title CB construction
#' @description The SVD-based constraint basis construction. Algorithm 1 from the reference.
#' @param A [nxk matrix] must have rank k
#' @return T (n x n) the basis matrix
#' @export
#'
c_basis1 <- function(A) {
    .Call(`_CB_c_basis1`, A)
}

#' @name c_basis2
#' @title CB construction
#' @description The SVD-based constraint basis construction for non-overlapping
#' subsets of constraints. Algorithm 1 from the reference.
#' Creating a basis from the matrix A
#' @param A [nxk matrix] must have rank k
#' @param eps_limit [double] used as a limit of small value
#' @return T (n x n) the basis matrix
#' @export
#'
c_basis2 <- function(A, eps_limit = 1e-10) {
    .Call(`_CB_c_basis2`, A, eps_limit)
}

#' @name likelihood
#' @title Likelihood
#' @return T (n x n) the basis matrix
#' @export
#'
likelihood <- function(Q) {
    .Call(`_CB_likelihood`, Q)
}

